### ISSUE TITLE
Support for NVENC acceleration for transcoding

### ISSUE THREAD

**Issue by Aterfax** [binhex/arch-jellyfin#2]
In theory this can probably be enabled from the AUR by using the following packages:

https://aur.archlinux.org/packages/ffmpeg-full-nvenc/
https://aur.archlinux.org/packages/nvidia-sdk/ (not needed if using the docker 'nvidia-runtime')

Then when ran with the nvidia-docker runtime it should pass a given GPU through from the host to the docker.

**Comment by Aterfax** [comment]
Having ran it in the nvidia-runtime for docker I currently get:

``` 
Stream mapping:
  Stream #0:0 (hevc_cuvid) -> overlay:main (graph 0)
  Stream #0:4 (pgssub) -> scale (graph 0)
  overlay (graph 0) -> Stream #0:0 (h264_nvenc)
  Stream #0:1 -> #0:1 (truehd (native) -> aac (native))
Press [q] to stop, [?] for help
[matroska,webm @ 0x55775555d900] sub2video: using 3840x1600 canvas
[h264_nvenc @ 0x55775558ee80] Driver does not support the required nvenc API version. Required: 9.0 Found: 8.1
[h264_nvenc @ 0x55775558ee80] The minimum required Nvidia driver for nvenc is 390.25 or newer
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P400         Off  | 00000000:07:00.0 Off |                  N/A |
| 26%   42C    P0    N/A /  N/A |      0MiB /  1999MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
Which I believe is directly related to the ffmpeg version since my nvidia-smi reports CUDA Version 10.0 and Driver version 410.78.

i.e. ffmpeg compiled with the wrong SDK version?

See: https://devtalk.nvidia.com/default/topic/1044184/driver-does-not-support-the-required-nvenc-api-version-required-8-2-found-8-1/

Edit: I appear to have this working inside the standard Jellyfin Docker image provided for unraid by compiling ffmpeg with the 10.0 CUDA SDK and installing the rest of the needed libraries for ffmpeg with NVENC.

**Comment by Aterfax** [comment]
Any chance we could get a more up to date NVENC enabled FFMPEG in the container? It should solve the issue above of HW acceleration with NVENC.

**Comment by Aterfax** [comment]
WRT the above - it would seem that having several FFMPEGs compiled for the different CUDA SDK versions is probably the best way to go about it - then the user can set Jellyfin to user the appropriate one.

I did this above for myself as I mentioned 

> 
> 
> Having ran it in the nvidia-runtime for docker I currently get:
> 
> ```
> Stream mapping:
>   Stream #0:0 (hevc_cuvid) -> overlay:main (graph 0)
>   Stream #0:4 (pgssub) -> scale (graph 0)
>   overlay (graph 0) -> Stream #0:0 (h264_nvenc)
>   Stream #0:1 -> #0:1 (truehd (native) -> aac (native))
> Press [q] to stop, [?] for help
> [matroska,webm @ 0x55775555d900] sub2video: using 3840x1600 canvas
> [h264_nvenc @ 0x55775558ee80] Driver does not support the required nvenc API version. Required: 9.0 Found: 8.1
> [h264_nvenc @ 0x55775558ee80] The minimum required Nvidia driver for nvenc is 390.25 or newer
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> ```
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Quadro P400         Off  | 00000000:07:00.0 Off |                  N/A |
> | 26%   42C    P0    N/A /  N/A |      0MiB /  1999MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```
> 
> Which I believe is directly related to the ffmpeg version since my nvidia-smi reports CUDA Version 10.0 and Driver version 410.78.
> 
> i.e. ffmpeg compiled with the wrong SDK version?
> 
> See: https://devtalk.nvidia.com/default/topic/1044184/driver-does-not-support-the-required-nvenc-api-version-required-8-2-found-8-1/
> 
> Edit: I appear to have this working inside the standard Jellyfin Docker image provided for unraid by compiling ffmpeg with the 10.0 CUDA SDK and installing the rest of the needed libraries for ffmpeg with NVENC.

**Comment by Aterfax** [comment]
This might help? Here's some existing FFMPEG NVENC automatic compile scripts:

 https://gist.github.com/Brainiarc7/3f7695ac2a0905b05c5b

https://github.com/ilyaevseev/ffmpeg-build

**Comment by Aterfax** [comment]
@binhex I think - from this point on the native Jellyfin project container will be taking care of FFMPEG being supplied compiled with the CUDA SDK / NVENC support.

The only important things to be aware of are keeping the installed driver SDK on the host in sync with the SDK version used to compile FFMPEG or issues like in comment 2 above can arise.

**Comment by binhex** [comment]
jellyfin compiled ffmpeg is now included in the image, please pull down latest tagged image.
