### ISSUE TITLE
High CPU-Load while IDLE - ffmpeg

### ISSUE THREAD

**Issue by eRaz3r** [binhex/arch-jellyfin#3]
I use the container and everything works well. A few days after install, the CPU-load starts to increase, even while the server is in idle. The process which cause this is the ffmpeg. Any idea, what I can do against this?

For example:
`nobody   31627 72.0  2.2 7032296 1122528 ?     Sl   08:59   2:19 /usr/bin/dotnet /usr/lib/jellyfin/jellyfin.dll --datadir /config/data --cachedir /config/cache --configdir /config/config --logdir /config/logs --ffmpeg /usr/bin/ffmpeg`

**Comment by binhex** [comment]
please try latest image as this now includes jellyfin compiled ffmpeg
