### ISSUE TITLE
Make use of jellyfin-ffmpeg5 

### ISSUE THREAD

**Issue by JoeGandy** [binhex/arch-jellyfin#4]
Is it possible to make use of jellyfin-ffmpeg5 in https://jellyfin.org/posts/jellyfin-10-8-0/ and above?

Specifically for enabling plugins like intro skipper: https://github.com/ConfusedPolarBear/intro-skipper

**Comment by JoeGandy** [comment]
Bump @binhex

**Comment by binhex** [comment]
I will see if I can take a look at this tonight

**Comment by Weevild** [comment]
Would appreciate this as well, +1

**Comment by binhex** [comment]
sorry for the delay guys, all done see here for the gory details:- https://github.com/binhex/arch-jellyfin/commit/396b20807217142f38b77cfb8c52e0440b457593

please pull down the latest image to see the change.
