### ISSUE TITLE
Since upgrading barely anything plays

### ISSUE THREAD

**Issue by JoeGandy** [binhex/arch-jellyfin#5]
I'd pulled https://github.com/binhex/arch-jellyfin/issues/4#event-7128474742 as it came out, most media won't play now

I saw we changed to /usr/lib/jellyfin-ffmpeg/ffmpeg for ffmpeg path so tried that in 'FFmpeg path:' in admin dashboard but no luck, some files will still play

When I hit play I get 

Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.

Just trying to find out if its a config issue on my end (likely!)

**Comment by binhex** [comment]
I dont actively use jellyfin myself, but gave this a quick test by adding in some media and then playing back numerous videos (1080p, mkv container format) and haven't seen any issues with any of the videos files to date. 
Are you using hardware transcoding?, if so try disabling that temporarily, also try playing the media via the web browser.

EDIT - Just for kicks i tried payback of a 4k Remux, again no issue when playing in web browser.

**Comment by binhex** [comment]
Yep i strongly suspect your issue is hardware transcoding related, i would think the media that plays back for you is NOT using the GPU and thus works. Check you have up to date drivers for your GPU.

**Comment by binhex** [comment]
Decided to write up a quick FAQ to detail how to enable hardware transcoding for Jellyfin:- https://github.com/binhex/documentation/blob/master/docker/faq/jellyfin.md

**Comment by JoeGandy** [comment]
I tried a fresh install and it all worked, so definitely not an issue in this repo! will close this and begin the painful migration
