### ISSUE TITLE
Intel Quicksync hardware transcode support

### ISSUE THREAD

**Issue by marco9663** [binhex/arch-jellyfin#7]
I find that Intel Quicksync hardware transcode is not supported out of the box. In Jellyfin web client, it always show `This client isn't compatible with the media and the server isn't sending a compatible media format.` warning when playing video with hardware transcoding on.

Following the [official documentation](https://jellyfin.org/docs/general/administration/hardware-acceleration/intel/#arch-linux), as this image is based on arch, I found out that after installing _User mode Intel media drivers and the OpenCL runtime_ with command 
`pacman -S libva-intel-driver intel-media-driver intel-media-sdk onevpl-intel-gpu intel-compute-runtime`  , 
hardware transcode with Intel Quicksync can then be used.

Verified with `intel_gpu_top`
<img width="643" alt="image" src="https://github.com/binhex/arch-jellyfin/assets/33394715/3d1fe5ff-839a-40d0-84b9-ed53177e0477">

**Environment:**
CPU: Intel i5-8400
GPU: UHD 630

**Comment by binhex** [comment]
Nice! Thanks for doing the leg work I shall include the packages in the next built image

**Comment by binhex** [comment]
Done, packages added to build script, next build will include the packages
